name: CMake Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  cmake-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build with Make
      run: |
        cd build
        make
